const data = [
    {
        type: 'Flood',
        date: '1931',
        region: 'CN',
        desc: "Yangtze Nehri'nin taşması sonucu meydana gelen sel felaketi, yaklaşık 4 milyon insanın ölümüne neden oldu.",
        name: '1931 Çin Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1887',
        region: 'CN',
        desc: "Sarı Nehir'in taşması sonucu meydana gelen sel felaketi, yaklaşık 900.000 ila 2 milyon insanın ölümüne neden oldu.",
        name: '1887 Sarı Nehir Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1938',
        region: 'CN',
        desc: "Japonya'nın Çin'e saldırısı sırasında Sarı Nehir'in taşması sonucu meydana gelen sel felaketi, yaklaşık 500.000 ila 900.000 insanın ölümüne neden oldu.",
        name: '1938 Sarı Nehir Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1975',
        region: 'CN',
        desc: "Nina Tayfunu'nun neden olduğu Banqiao Barajı'nın çökmesi sonucu meydana gelen sel felaketi, yaklaşık 231.000 insanın ölümüne neden oldu.",
        name: '1975 Banqiao Barajı Felaketi',
    },
    {
        type: 'Flood',
        date: '1935',
        region: 'CN',
        desc: "Yangtze Nehri'nin taşması sonucu meydana gelen sel felaketi, yaklaşık 145.000 insanın ölümüne neden oldu.",
        name: '1935 Yangtze Nehri Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1911',
        region: 'CN',
        desc: 'Yangtze ve Huai nehirlerinin taşması sonucu meydana gelen sel felaketi, yaklaşık 100.000 insanın ölümüne neden oldu.',
        name: '1911 Jiangsu-Anhui Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1971',
        region: 'VN',
        desc: "Red River Delta'da meydana gelen sel felaketi, yaklaşık 100.000 insanın ölümüne neden oldu.",
        name: '1971 Red River Delta Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1939',
        region: 'CN',
        desc: "Yangtze Nehri'nin taşması sonucu meydana gelen sel felaketi, yaklaşık 100.000 insanın ölümüne neden oldu.",
        name: '1939 Yangtze Nehri Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1287',
        region: 'NL',
        desc: "St. Lucia seli, Hollanda ve Kuzey Almanya'da 50.000 ila 80.000 insanın ölümüne neden oldu.",
        name: '1287 St. Lucia Sel Felaketi',
    },
    {
        type: 'Flood',
        date: '1212',
        region: 'NL',
        desc: "Kuzey Denizi seli, Hollanda'da yaklaşık 60.000 insanın ölümüne neden oldu.",
        name: '1212 Kuzey Denizi Sel Felaketi',
    },
    {
        type: 'Earthquake',
        date: '1960-05-22',
        region: 'CL',
        desc: "9.5 büyüklüğündeki bu deprem, Şili'de büyük yıkıma ve tsunamilere neden oldu. Yaklaşık 1.655 kişi hayatını kaybetti.",
        name: '1960 Valdivia Depremi',
    },
    {
        type: 'Earthquake',
        date: '1964-03-27',
        region: 'US',
        desc: "9.2 büyüklüğündeki bu deprem, Alaska'da büyük yıkıma ve tsunamilere neden oldu. 128 kişi hayatını kaybetti.",
        name: '1964 Alaska Depremi',
    },
    {
        type: 'Earthquake',
        date: '2004-12-26',
        region: 'ID',
        desc: "9.1 büyüklüğündeki bu deprem, Hint Okyanusu'nda büyük bir tsunamiye neden oldu. Yaklaşık 230.000 kişi hayatını kaybetti.",
        name: '2004 Hint Okyanusu Depremi',
    },
    {
        type: 'Earthquake',
        date: '2011-03-11',
        region: 'JP',
        desc: "9.0 büyüklüğündeki bu deprem, Japonya'da büyük bir tsunamiye neden oldu. Yaklaşık 15.900 kişi hayatını kaybetti.",
        name: '2011 Tohoku Depremi',
    },
    {
        type: 'Earthquake',
        date: '1952-11-04',
        region: 'RU',
        desc: "9.0 büyüklüğündeki bu deprem, Kamçatka Yarımadası'nda büyük bir tsunamiye neden oldu.",
        name: '1952 Kamçatka Depremi',
    },
    {
        type: 'Earthquake',
        date: '2010-02-27',
        region: 'CL',
        desc: "8.8 büyüklüğündeki bu deprem, Şili'de büyük yıkıma ve tsunamilere neden oldu. 525 kişi hayatını kaybetti.",
        name: '2010 Şili Depremi',
    },
    {
        type: 'Earthquake',
        date: '1906-01-31',
        region: 'EC',
        desc: "8.8 büyüklüğündeki bu deprem, Ekvador ve Kolombiya'da büyük yıkıma ve tsunamilere neden oldu.",
        name: '1906 Ekvador-Kolombiya Depremi',
    },
    {
        type: 'Earthquake',
        date: '1965-02-04',
        region: 'US',
        desc: "8.7 büyüklüğündeki bu deprem, Alaska'da büyük yıkıma neden oldu.",
        name: '1965 Rat Adaları Depremi',
    },
    {
        type: 'Earthquake',
        date: '2005-03-28',
        region: 'ID',
        desc: "8.6 büyüklüğündeki bu deprem, Endonezya'da büyük yıkıma neden oldu. Yaklaşık 1.300 kişi hayatını kaybetti.",
        name: '2005 Nias-Simeulue Depremi',
    },
    {
        type: 'Earthquake',
        date: '2001-01-26',
        region: 'IN',
        desc: "7.7 büyüklüğündeki bu deprem, Hindistan'ın Gujarat eyaletinde büyük yıkıma neden oldu. Yaklaşık 20.000 kişi hayatını kaybetti.",
        name: '2001 Gujarat Depremi',
    },
    {
        type: 'Landslide',
        date: '1920-12-16',
        region: 'CN',
        desc: 'Gansu eyaletinde meydana gelen deprem sonrası oluşan heyelan, yaklaşık 200.000 kişinin ölümüne neden oldu.',
        name: '1920 Gansu Heyelanı',
    },
    {
        type: 'Landslide',
        date: '1970-05-31',
        region: 'PE',
        desc: "Peru'da Huascarán Dağı'ndan kopan büyük bir buz ve kaya kütlesi, Yungay kasabasını yok etti ve yaklaşık 20.000 kişinin ölümüne neden oldu.",
        name: '1970 Huascarán Heyelanı',
    },
    {
        type: 'Landslide',
        date: '1985-11-13',
        region: 'CO',
        desc: 'Nevado del Ruiz volkanının patlaması sonucu oluşan heyelan, Armero kasabasını yok etti ve yaklaşık 23.000 kişinin ölümüne neden oldu.',
        name: '1985 Armero Tragedyası',
    },
    {
        type: 'Landslide',
        date: '2013-06-16',
        region: 'IN',
        desc: "Hindistan'ın Uttarakhand eyaletinde meydana gelen şiddetli yağışlar sonucu oluşan heyelanlar ve seller, yaklaşık 5.700 kişinin ölümüne neden oldu.",
        name: '2013 Uttarakhand Felaketi',
    },
    {
        type: 'Landslide',
        date: '1999-12-14',
        region: 'VE',
        desc: "Venezuela'nın Vargas eyaletinde meydana gelen şiddetli yağışlar sonucu oluşan heyelanlar, yaklaşık 30.000 kişinin ölümüne neden oldu.",
        name: '1999 Vargas Tragedyası',
    },
    {
        type: 'Landslide',
        date: '2014-03-22',
        region: 'US',
        desc: 'Washington eyaletinde meydana gelen heyelan, Oso kasabasını vurdu ve 43 kişinin ölümüne neden oldu.',
        name: '2014 Oso Heyelanı',
    },
    {
        type: 'Landslide',
        date: '2006-02-17',
        region: 'PH',
        desc: "Filipinler'in Leyte adasında meydana gelen heyelan, Guinsaugon köyünü yok etti ve yaklaşık 1.126 kişinin ölümüne neden oldu.",
        name: '2006 Guinsaugon Heyelanı',
    },
    {
        type: 'Landslide',
        date: '2017-08-14',
        region: 'SL',
        desc: "Sierra Leone'nin başkenti Freetown'da meydana gelen heyelan, yaklaşık 1.141 kişinin ölümüne neden oldu.",
        name: '2017 Freetown Heyelanı',
    },
    {
        type: 'Landslide',
        date: '1963-10-09',
        region: 'IT',
        desc: "Vajont Barajı'nın çökmesi sonucu oluşan heyelan, yaklaşık 2.000 kişinin ölümüne neden oldu.",
        name: '1963 Vajont Barajı Felaketi',
    },
    {
        type: 'Landslide',
        date: '2018-09-28',
        region: 'ID',
        desc: "Endonezya'nın Sulawesi adasında meydana gelen deprem sonrası oluşan heyelan, yaklaşık 4.340 kişinin ölümüne neden oldu.",
        name: '2018 Sulawesi Depremi ve Heyelanı',
    },
    {
        type: 'Fire',
        date: '1871-10-08',
        region: 'US',
        desc: "Chicago'da başlayan ve üç gün süren yangın, yaklaşık 300 kişinin ölümüne ve 100.000 kişinin evsiz kalmasına neden oldu.",
        name: '1871 Büyük Chicago Yangını',
    },
    {
        type: 'Fire',
        date: '1910-08-20',
        region: 'US',
        desc: "Kuzey Idaho ve Batı Montana'da başlayan yangın, yaklaşık 3 milyon akre alanı yok etti ve 87 kişinin ölümüne neden oldu.",
        name: '1910 Büyük Ateş (Big Burn)',
    },
    {
        type: 'Fire',
        date: '1666-09-02',
        region: 'GB',
        desc: "Londra'da başlayan ve dört gün süren yangın, şehrin büyük bir kısmını yok etti ve binlerce insanı evsiz bıraktı.",
        name: '1666 Büyük Londra Yangını',
    },
    {
        type: 'Fire',
        date: '2019-08-01',
        region: 'BR',
        desc: "Amazon Ormanları'nda başlayan yangın, büyük bir çevresel felakete yol açtı ve geniş alanları yok etti.",
        name: '2019 Amazon Orman Yangınları',
    },
    {
        type: 'Fire',
        date: '2009-02-07',
        region: 'AU',
        desc: "Victoria eyaletinde başlayan yangın, 173 kişinin ölümüne ve 2.000'den fazla evin yıkılmasına neden oldu.",
        name: '2009 Kara Cumartesi Yangınları',
    },
    {
        type: 'Fire',
        date: '2018-11-08',
        region: 'US',
        desc: "California'da başlayan yangın, 85 kişinin ölümüne ve 18.000'den fazla yapının yıkılmasına neden oldu.",
        name: '2018 Camp Yangını',
    },
    {
        type: 'Fire',
        date: '1987-05-06',
        region: 'CN',
        desc: "Daxing'anling bölgesinde başlayan yangın, yaklaşık 3 milyon akre alanı yok etti ve 191 kişinin ölümüne neden oldu.",
        name: "1987 Daxing'anling Yangını",
    },
    {
        type: 'Fire',
        date: '1825-10-07',
        region: 'US',
        desc: "Maine ve New Brunswick'te başlayan yangın, yaklaşık 3 milyon akre alanı yok etti.",
        name: '1825 Miramichi Yangını',
    },
    {
        type: 'Fire',
        date: '1871-10-08',
        region: 'US',
        desc: "Wisconsin'de başlayan yangın, yaklaşık 1.200 kişinin ölümüne ve 1.2 milyon akre alanın yok olmasına neden oldu.",
        name: '1871 Peshtigo Yangını',
    },
    {
        type: 'Fire',
        date: '2020-09-09',
        region: 'US',
        desc: "California'da başlayan yangınlar, geniş alanları yok etti ve büyük bir çevresel felakete yol açtı.",
        name: '2020 California Yangınları',
    },
    {
        type: 'Avalanche',
        date: '1970-05-31',
        region: 'PE',
        desc: "Peru'da Huascarán Dağı'ndan kopan büyük bir buz ve kaya kütlesi, Yungay kasabasını yok etti ve yaklaşık 20.000 kişinin ölümüne neden oldu.",
        name: '1970 Huascarán Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1916-12-13',
        region: 'IT',
        desc: "I. Dünya Savaşı sırasında İtalyan Alpleri'nde meydana gelen çığ, yaklaşık 10.000 Avusturya ve İtalyan askerinin ölümüne neden oldu.",
        name: '1916 Alpler Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '2010-02-08',
        region: 'AF',
        desc: "Afganistan'ın Salang Geçidi'nde meydana gelen çığ, yaklaşık 172 kişinin ölümüne neden oldu.",
        name: '2010 Salang Geçidi Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1951-01-09',
        region: 'AT',
        desc: "Avusturya'da Blons köyünde meydana gelen çığ, yaklaşık 200 kişinin ölümüne neden oldu.",
        name: '1951 Blons Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1993-07-11',
        region: 'JP',
        desc: "Japonya'nın Hokkaido adasında meydana gelen çığ, 141 kişinin ölümüne neden oldu.",
        name: '1993 Hokkaido Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1962-01-11',
        region: 'IR',
        desc: "İran'ın Shemiranat bölgesinde meydana gelen çığ, yaklaşık 4.000 kişinin ölümüne neden oldu.",
        name: '1962 Shemiranat Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '2012-04-07',
        region: 'PK',
        desc: "Pakistan'ın Siachen bölgesinde meydana gelen çığ, 129 askerin ve 11 sivilin ölümüne neden oldu.",
        name: '2012 Siachen Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1990-02-15',
        region: 'TR',
        desc: "Türkiye'nin Van ilinde meydana gelen çığ, 60 kişinin ölümüne neden oldu.",
        name: '1990 Van Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '1999-02-09',
        region: 'AT',
        desc: "Avusturya'nın Galtür kasabasında meydana gelen çığ, 31 kişinin ölümüne neden oldu.",
        name: '1999 Galtür Çığ Felaketi',
    },
    {
        type: 'Avalanche',
        date: '2015-04-25',
        region: 'NP',
        desc: "Nepal'de Everest Dağı'nda meydana gelen çığ, 22 kişinin ölümüne neden oldu.",
        name: '2015 Everest Çığ Felaketi',
    },
    {
        type: 'Other',
        date: '2004-12-26',
        region: 'ID',
        desc: "Hint Okyanusu'nda meydana gelen 9.1 büyüklüğündeki deprem sonrası oluşan tsunami, yaklaşık 230.000 kişinin ölümüne neden oldu.",
        name: '2004 Hint Okyanusu Tsunamisi',
    },
    {
        type: 'Other',
        date: '2005-08-29',
        region: 'US',
        desc: 'Kategori 5 seviyesindeki Katrina Kasırgası, New Orleans ve çevresinde büyük yıkıma neden oldu. Yaklaşık 1.800 kişi hayatını kaybetti.',
        name: '2005 Katrina Kasırgası',
    },
    {
        type: 'Other',
        date: '2013-11-08',
        region: 'PH',
        desc: "Haiyan Tayfunu, Filipinler'de büyük yıkıma neden oldu ve yaklaşık 6.300 kişinin ölümüne yol açtı.",
        name: '2013 Haiyan Tayfunu',
    },
    {
        type: 'Other',
        date: '1815-04-10',
        region: 'ID',
        desc: "Tambora Dağı'nın patlaması, yaklaşık 71.000 kişinin ölümüne neden oldu ve küresel iklim değişikliklerine yol açtı.",
        name: '1815 Tambora Patlaması',
    },
    {
        type: 'Other',
        date: '1983',
        region: 'ET',
        desc: "Etiyopya'da meydana gelen büyük kuraklık, yaklaşık 1 milyon kişinin ölümüne neden oldu.",
        name: '1983 Etiyopya Kuraklığı',
    },
    {
        type: 'Other',
        date: '1989-04-26',
        region: 'BD',
        desc: "Bangladeş'te meydana gelen tornado, yaklaşık 1.300 kişinin ölümüne ve 12.000 kişinin yaralanmasına neden oldu.",
        name: '1989 Daulatpur-Saturia Tornadosu',
    },
    {
        type: 'Other',
        date: '1972-02-03',
        region: 'IR',
        desc: "İran'da meydana gelen şiddetli kış fırtınası, yaklaşık 4.000 kişinin ölümüne neden oldu.",
        name: '1972 İran Kış Fırtınası',
    },
    {
        type: 'Other',
        date: '1930',
        region: 'US',
        desc: "ABD'nin Orta Batı bölgesinde meydana gelen büyük kuraklık ve toprak erozyonu, binlerce çiftçinin göç etmesine neden oldu.",
        name: "1930'lar Dust Bowl",
    },
    {
        type: 'Other',
        date: '1998-01-04',
        region: 'CA',
        desc: "Kanada'nın doğusunda meydana gelen buz fırtınası, geniş çaplı elektrik kesintilerine ve büyük hasara neden oldu.",
        name: '1998 Kuzey Amerika Buz Fırtınası',
    },

];

export default data;
