const data = [
    {
        history_id: 1,
        history_name: 'Landslide',
        history_date: '2021-01-01',
        history_region: 'US',
        history_desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 2,
        history_name: 'Flood',
        history_date: '2021-02-15',
        history_region: 'CA',
        history_desc: 'Flooding in major areas caused extensive damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 3,
        history_name: 'Earthquake',
        history_date: '2021-03-10',
        history_region: 'JP',
        history_desc: 'A powerful earthquake struck the region, causing widespread destruction. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 4,
        history_name: 'Flood',
        history_date: '2021-04-05',
        history_region: 'MX',
        history_desc: 'Hurricane brought heavy rains and strong winds, leading to significant damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 5,
        history_name: 'Wildfire',
        history_date: '2021-05-20',
        history_region: 'AU',
        history_desc: 'Wildfires spread rapidly, consuming large areas of forest and threatening homes. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 6,
        history_name: 'Tornado',
        history_date: '2021-06-25',
        history_region: 'US',
        history_desc: 'A destructive tornado swept through the region, causing severe damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 7,
        history_name: 'Earthquake',
        history_date: '2021-07-30',
        history_region: 'ID',
        history_desc: 'A massive tsunami hit the coast, leading to widespread devastation. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 8,
        history_name: 'Drought',
        history_date: '2021-08-15',
        history_region: 'ZA',
        history_desc: 'Severe drought conditions affected many regions, leading to water shortages. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 9,
        history_name: 'Blizzard',
        history_date: '2021-09-10',
        history_region: 'RU',
        history_desc: 'A powerful blizzard caused significant disruption and damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 10,
        history_name: 'Wildfire',
        history_date: '2021-10-05',
        history_region: 'IS',
        history_desc: 'A volcanic eruption resulted in ash clouds and lava flow, impacting nearby areas. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 11,
        history_name: 'Earthquake',
        history_date: '2021-11-01',
        history_region: 'CL',
        history_desc: 'A significant earthquake hit the region, causing considerable damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 12,
        history_name: 'Flood',
        history_date: '2021-12-10',
        history_region: 'DE',
        history_desc: 'Severe flooding affected multiple regions, leading to substantial losses. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 13,
        history_name: 'Wildfire',
        history_date: '2022-01-15',
        history_region: 'BR',
        history_desc: 'Wildfires in the Amazon caused extensive environmental damage. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 14,
        history_name: 'Landslide',
        history_date: '2022-02-20',
        history_region: 'IN',
        history_desc: 'A landslide in the Himalayan region led to significant casualties. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 15,
        history_name: 'Earthquake',
        history_date: '2022-03-05',
        history_region: 'TR',
        history_desc: 'A powerful earthquake caused widespread destruction and loss of life. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 16,
        history_name: 'Flood',
        history_date: '2022-04-10',
        history_region: 'BD',
        history_desc: 'Heavy rains caused severe flooding, displacing thousands of people. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 17,
        history_name: 'Landslide',
        history_date: '2022-05-15',
        history_region: 'NP',
        history_desc: 'A massive landslide buried several villages, causing significant casualties. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 18,
        history_name: 'Wildfire',
        history_date: '2022-06-20',
        history_region: 'US',
        history_desc: 'Wildfires spread rapidly, threatening homes and natural reserves. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
    {
        history_id: 19,
        history_name: 'Earthquake',
        history_date: '2022-07-25',
        history_region: 'NZ',
        history_desc: 'A strong earthquake struck, causing damage to infrastructure and homes. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Assumenda, odit a? Vitae delectus fugiat similique doloribus error quia nemo asperiores expedita, sed architecto temporibus, optio mollitia pariatur natus perspiciatis amet!',
    },
];

export default data;
